# Generated by Django 4.2.4 on 2023-08-26 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_payment_type', models.CharField(choices=[('CASH', 'cash'), ('CHECKS', 'checks'), ('DEBIT CARDS', 'debit cards'), ('CREDIT CARDS', 'credit cards'), ('MOBILE PAYMENTS', 'mobile payments'), ('ELECTRONIC BANK TRANSFERS', 'electronic bank transfers')], max_length=150)),
                ('provider', models.CharField(max_length=150)),
                ('account_no', models.IntegerField()),
                ('expiry', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=150)),
                ('address_line2', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=150)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
