# Generated by Django 4.2.4 on 2023-08-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='provider',
            field=models.CharField(choices=[('humo', 'HUMO'), ('uzcard', 'UzCard'), ('visa', 'VISA'), ('mastercard', 'MasterCard')], max_length=150),
        ),
    ]
