# Generated by Django 4.2.4 on 2023-08-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userpayment_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
