# Generated by Django 4.2.1 on 2023-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopp', '0002_product_photo1_product_photo2_product_photo3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('UZS', 'uzs'), ('EURO', 'euro'), ('USD', 'usd')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
