# Generated by Django 4.2.4 on 2023-08-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopp', '0010_orderitems_user_alter_paymentdetail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='user',
        ),
    ]
