# Generated by Django 4.2.4 on 2023-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopp', '0014_cartitem_price_cartitem_total_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(max_length=10),
        ),
    ]
