# Generated by Django 4.2.4 on 2023-08-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopp', '0018_cart_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('uzs', 'UZS'), ('euro', 'EURO'), ('usd', 'USD')], max_length=10, null=True),
        ),
    ]
