# Generated by Django 4.2.4 on 2023-08-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopp', '0019_alter_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='status',
            field=models.CharField(choices=[('no paid', 'NO PAID'), ('paid', 'PAID')], max_length=255),
        ),
    ]
