# Generated by Django 4.2.7 on 2023-11-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinika', '0003_alter_blog_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.ManyToManyField(blank=True, to='clinika.video'),
        ),
    ]
