# Generated by Django 4.2.7 on 2023-11-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinika', '0004_video_blog_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video',
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinika.video'),
        ),
    ]
