# Generated by Django 4.2.7 on 2023-11-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinika', '0006_remove_blog_video_blog_video_url_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video_url',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
